version: "3.8"
services:

  db-team-retro:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: team_retro_db
      POSTGRES_USER: team_retro_db_admin
      POSTGRES_PASSWORD: team_retro_db_admin_password
    volumes:
      - ./docker/db/team-retro-service/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - "5469:5432"

  nginx-srv:
    image: nginx:1.25.2-alpine
    container_name: nginx-srv
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/conf/ssl:/etc/nginx/ssl
    environment:
      TZ: "Europe/Moscow"