spring:
  main.web-application-type: none
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5469}/${DB_NAME:team_retro_db}?reWriteBatchedInserts=true
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${spring.datasource.url}
      username: ${DB_USER:team_retro_db_admin}
      password: ${DB_PASSWORD:team_retro_db_admin_password}
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        ddl-auto: none
        order_inserts: true
        jdbc.time_zone: Europe/Moscow
        jdbc.batch_size: 5000
        jdbc.lob.non_contextual_creation: true
        format_sql: false
    open-in-view: false
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog.yaml
    contexts: main
    enabled: true
    default-schema: public