### Создание нового ретро
POST {{base_url}}/api/v1/retro
Authorization: {{auth_token}}
Content-Type: application/json

{
  "caption": "This is retro caption",
  "description": "This is retro description"
}

<> end-request-body

### Получение списка ретро
GET {{base_url}}/api/v1/retro/list?
    pageNumber=0&
    pageSize=2
Authorization: {{auth_token}}
Content-Type: application/json

### Получение параметров ретро
GET {{base_url}}/api/v1/retro/94d52e48-fe72-4bd8-86bd-83a71a9db96d
Authorization: {{auth_token}}
Content-Type: application/json

### Обновление параметров ретро
PUT {{base_url}}/api/v1/retro/bf661e0c-cba9-4a26-9cfc-a2874db0e402
Authorization: {{auth_token}}
Content-Type: application/json

{
  "caption": "new caption",
  "description": "new description"
}

<> end-request-body

### Удаление ретро
DELETE {{base_url}}/api/v1/retro/1755b7ab-690e-498b-9e68-4946bdb26cf1
